import clsx from "clsx";
import {
  inspectionOptions,
  inspectionPackContents,
  inspectionValueFraming,
} from "@/lib/content/pricing";

export function InspectionPackagesBlock({ id, compact = false }: { id?: string; compact?: boolean }) {
  return (
    <div id={id} className="scroll-mt-24">
      <p className="max-w-2xl text-slate-500">
        Generated by the Registered Manager from data across the whole platform, into one
        branded, inspector-ready PDF. Priced per organisation or site, not per seat.
      </p>

      {!compact && (
        <div className="mt-6 flex flex-wrap gap-2">
          {inspectionPackContents.map((item) => (
            <span
              key={item}
              className="rounded-full border border-navy-100 bg-offwhite px-3 py-1 font-mono text-xs text-navy-900"
            >
              {item}
            </span>
          ))}
        </div>
      )}

      <ul className="mt-8 grid gap-6 lg:grid-cols-3">
        {inspectionOptions.map((option) => (
          <li key={option.key}>
            <div
              className={clsx(
                "h-full rounded-lg border p-8",
                option.recommended
                  ? "border-teal-600 bg-navy-900 text-white shadow-card-dark"
                  : "border-navy-100 bg-white text-navy-900",
              )}
            >
              {option.recommended && (
                <span className="mb-4 inline-flex w-fit rounded-full bg-teal-500/15 px-3 py-1 font-mono text-[11px] uppercase tracking-widest text-teal-400">
                  Recommended
                </span>
              )}
              <h3 className="font-heading text-lg font-semibold">{option.name}</h3>
              <div className="mt-4 flex items-baseline gap-2">
                <span className="font-mono text-3xl font-semibold">{option.price}</span>
                <span className={clsx("text-sm", option.recommended ? "text-white/70" : "text-slate-500")}>
                  {option.description}
                </span>
              </div>
              {!compact && (
                <ul className="mt-6 space-y-3">
                  {option.features.map((feature) => (
                    <li key={feature} className="flex items-start gap-2 text-sm">
                      <span
                        className={clsx(
                          "mt-1 h-1.5 w-1.5 shrink-0 rounded-full",
                          option.recommended ? "bg-teal-400" : "bg-teal-600",
                        )}
                        aria-hidden="true"
                      />
                      <span className={option.recommended ? "text-white/80" : "text-slate-600"}>{feature}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </li>
        ))}
      </ul>

      <div className="mt-8 rounded-lg bg-brand-gradient p-8">
        <p className="font-heading text-lg font-semibold text-white">
          {inspectionValueFraming.heading}
        </p>
        <p className="mt-3 max-w-3xl text-white/85">{inspectionValueFraming.body}</p>
      </div>
    </div>
  );
}
